fix(bump_version): cannot sign using CI gpg key (#168)
* test: test bump_version with a commit

* test(bump_version): specify git user

* ci: add depth to bump_version test

* ci: fix invalid field name

* test: remove useless command

* test: trim trailing space in name

* test: specify signing key

* test: export GPG_TTY

* test: use TTY

* test: preset passphrase

* test: dynamically get preset directory

* test: extract correct line

* test: allow to preset passhrase

* test: restart agent

* test: use keygrip

* test: get correct keygrip

* test: add quotes

* test: allow pinetry

* test: fix syntax

* test: use temp script for gpg

* test: fix script

* test: fix script

* test: use key id

* test: use keygrip

* test: fix invalid syntax

* test: preset key_id

* test: use files

* test: invalid variable

* test: reload

* test: add --no-tty

* test: fix keygrip

* test: add more output

* test: rearragne

* test: show more info

* test: get keygrip inof

* test: add more presets

* test: add more presets

* test: add another config

* test: more diag

* test: start daemon

* test: preset passhrrase using connect

* test: changes

* test: add /bye

* test: use custom gpg command

* test: use another keygrips

* test: use another keygrips

* test: use another keygrips

* test: use array

* test: changes

* test: changes

* test: changes

* test: changes

* test: changes

* test: changes

* test: changes

* test: provide passphrase directly

* test: fix invalid command

* test: fix invalid command

* test: fix invalid command

* test: fix invalid command

* test: set pinentry mode

* test: change order

* test: fix invalid passphrase

* test: fix invalid passphrase

* test: fix invalid passphrase

diff --git a/ci/scripts/bump_version b/ci/scripts/bump_version
--- a/ci/scripts/bump_version
+++ b/ci/scripts/bump_version
@@ -3,27 +3,58 @@ set -Eeuxo pipefail
 
 (
     set +x
-    private_key="${CI_GPG_PRIVATE_KEY:?missing gpg private key}"
-    passphrase="${CI_GPG_PASSPHRASE:?missing gpg passphrase}"
-    echo "${passphrase}" |
-        gpg --batch --yes --import <(echo "${private_key}")
+    printf "%s" "${CI_GPG_PRIVATE_KEY:?missing gpg private key}" >_key
+    printf "%s" "${CI_GPG_PASSPHRASE:?missing gpg passphrase}" >_passphrase
 )
 
-info=$(gpg --with-colons --batch --list-secret-keys | awk -F "::" '/uid/ { print $5 }')
-name="${info%%<*}"
-email="${info##*<}"
-email="${email::-1}"
+key=$(gpg --with-colons --batch --show-keys --with-fingerprint --keyid-format=long _key)
+user=$(awk -F ":" '/uid/ { print $10 }' <<<"${key}")
+key_id=$(awk -F ":" '/sec/ { print $5 }' <<<"${key}")
+fingerprint=$(awk -F ":" '/fpr/ { print $10; exit }' <<<"${key}")
+keygrip=$(awk -F ":" '/fpr/ { keygrip = $10 } END { print keygrip }' <<<"${key}")
 
+echo '\
+#!/usr/bin/env bash
+set -Eeux
+gpg \
+    --batch \
+    -vv \
+    --yes \
+    --no-tty \
+    --passphrase-file _passphrase \
+    --pinentry-mode loopback \
+    "${@}"
+' >_gpg.sh
+chmod +x _gpg.sh
+echo "
+default-cache-ttl 21600
+max-cache-ttl 31536000
+allow-preset-passphrase
+allow-loopback-pinentry
+" >>"${HOME}/.gnupg/gpg-agent.conf"
+gpg-connect-agent reloadagent /bye
+./_gpg.sh --import _key
+
+
+name="${user%%<*}"
+name="${name::-1}"
+email="${user##*<}"
+email="${email::-1}"
 export GIT_AUTHOR_NAME="${name}"
 export GIT_AUTHOR_EMAIL="${email}"
 export GIT_COMMITTER_NAME="${name}"
 export GIT_COMMITTER_EMAIL="${email}"
 
+git status
+git config user.signingkey "${key_id}"
+git config gpg.program "${PWD}/_gpg.sh"
+git config commit.gpgsign true
+git config tag.gpgsign true
+
 python3 -m venv .venv
 . .venv/bin/activate
 pip install commitizen=="3.13.0"
-git status
-cz bump --yes --changelog --version-scheme semver || {
+cz bump --yes --version-scheme semver || {
     code="${?}"
     if [[ "${code}" -eq 21 ]]; then
         echo "NonIncrementExit detected, exiting"
@@ -35,7 +66,7 @@ cz bump --yes --changelog --version-scheme semver || {
 
 new_tag="v$(cz version -p)"
 git tag -v "${new_tag}"
-if [[ ! "${DRY_RUN:-}" ]]; then
+if [[ -z "${DRY_RUN:-}" ]]; then
     git push origin HEAD
     git push origin "${new_tag}"
 fi
